


export const profileData = [
    {
        id: 1,
        name: 'Jun Dave Wamar',
        position: 'Full Stack Developer',
        quote: 'As an inspiring full stack web developer with 2 years of experience, you excel at crafting dynamic and responsive websites.',
        image1: require('../../assets/images/profile/dave1.png'),
        image2: require('../../assets/images/profile/dave2.png'),
        image3: require('../../assets/images/profile/dave3.png'),
        profilePic: require('../../assets/images/profile/dave5.png'),
        friends: 500,
        content: '2.5M',
        followers: '10M',
      },  
      {
        id:3,
        name: 'Weljie Pitogo',
        position: 'Database Manager',
        quote:'Enthusiastic and Competent Database Manager',
        image1:require('../../assets/images/profile/weljie1.png'),
        image2:require('../../assets/images/profile/weljie2.png'),
        image3:require('../../assets/images/profile/weljie3.png'),
        profilePic:require('../../assets/images/profile/weljie5.png'),
        friends:763,
        content: '6.5M',
        followers:'12M',
    },
    {
        id:2,
        name: 'Ryan Kane Boltron',
        position: 'UI/UX Designer',
        quote:'As an aspiring UI/UX designer, I am passionate about creating intuitive and engaging digital experiences that captivate users.',
        image1:  require('../../assets/images/profile/boltron1.png'),
        image2:  require('../../assets/images/profile/boltron2.png'),
        image3:  require('../../assets/images/profile/boltron3.png'),
        profilePic:  require('../../assets/images/profile/boltron5.png'),
        friends:573,
        content: '3.5M',
        followers:'7M',
    },
  
    {
        id:4,
        name: 'Vince Parco',
        position: 'WordPress Developer',
        quote:'A WordPress developer and graphics artist continuously refining my skills to deliver exceptional results.',
        image1:require('../../assets/images/profile/vince1.png'),
        image2:require('../../assets/images/profile/vince2.png'),
        image3:require('../../assets/images/profile/vince3.png'),
        profilePic: require('../../assets/images/profile/vince5.png'),
        friends:763,
        content: '2.5M',
        followers:'6M',
    },
    {
        id:5,
        name: 'Marianne Bueta',
        position: 'UI/UX Designer',
        quote:'As an aspiring UI/UX designer, to bring a keen eye for detail and a passion for creating visually appealing and user-friendly interfaces.',
        image1:require('../../assets/images/profile/bueta1.png'),
        image2:require('../../assets/images/profile/bueta2.png'),
        image3: require('../../assets/images/profile/bueta3.png'),
        profilePic: require('../../assets/images/profile/bueta5.png'),
        friends:699,
        content: '9.5M',
        followers:'25M',
    },
    
] 